# 调试模式：生产环境请关闭此项
debug: true
logger:
  level: info

port:
  protocol: "tcp"
  fingerprint_file: "config/fingerprint/nmap-service-probes"
  target_ips:
    - "192.168.64.13"
#    - "192.168.0.0/24"
  target_ports:
#    - "1443"
    - "22"
    - "111"
#    - "445"
#    - "8161"
#    - "3306"
#    - "135"
#    - "5980"
#    - "21"
#    - "23"
#    - "80-90"
#    - "2049"
#    - "8080-8090"
#    - "8443"
  timeout: 1
  thread: 10
  retry: 3