# 配置文件模板
debug: true
logger:
  level: debug
redis:
  uri: redis://:password@redis:6379/0
  sentinel: false
  password: password
  master_name: master
  sentinel_addrs:
    - redis:6379
  db: 0
Database:
  DSN: "postgres://postgres:postgres@localhost/test"
  LogMode: false
  MaxIdleConns: 0
  MaxOpenConns: 0
  ConnMaxLifetime: 0

port:
  protocol: "tcp"
  fingerprint_file: "fingerprint/nmap-service-probes"
  target_ips:
    - "192.168.1.100"
  target_ports:
    - "1443"
    - "22"
    - "445"
    - "8161"
    - "3306"
    - "135"
    - "5980"
    - "80-90"
    - "8080-8090"
  timeout: 5
  thread: 20
  retry: 3

blasting:
  target-host: "target.txt"
  user-file: "user.txt"
  pass-file: "pass.txt"
  delay: 0
  thread: 100
  timeout: 0
  retry: 0
  scan-port: false
  services:
    - "ssh"
    - "ftp"
    - "mssql"
    - "mysql"
    - "redis"
    - "postgresql"
    - "oracle"
    - "http_basic"
    - "tomcat"
    - "telnet"
  path: "/login"
  tomcat-path: "/manager"