# 配置文件模板
debug: true
disable-stacktrace: true # 是关闭印错误栈
logger:
  level: debug
redis:
  uri: redis://:password@redis:6379/0
  sentinel: false
  password: password
  master_name: master
  sentinel_addrs:
    - redis:6379
  db: 0
Database:
  DSN: "postgres://postgres:postgres@localhost/test"
  LogMode: false
  MaxIdleConns: 0
  MaxOpenConns: 0
  ConnMaxLifetime: 0

port:
  protocol: "tcp"
  fingerprint-file: "fingerprint/nmap-service-probes"
  target-ips:
    - "192.168.1.100"
  target-file: "target-host.txt"
  target-ports:
    - "1443"
    - "22"
    - "445"
    - "8161"
    - "3306"
    - "135"
    - "5980"
    - "80-90"
    - "8080-8090"

brute:
  target-host: "target.txt"
  user-file: "user.txt"
  pass-file: "pass.txt"
  scan-port: false
  services:
    - "ssh"
    - "ftp"
    - "mssql"
    - "mysql"
    - "redis"
    - "postgresql"
    - "http_basic"
    - "tomcat"
    - "telnet"
  path: "/login"
  tomcat-path: "/manager"

web:
  target-urls: "urls.txt"
  target-ports:
    - 80
    - 443
  fingerprint-name: "fingerprint/finger.json"

cyberspace:
  engine: "fofa"
  search: ""
  fofa:
    authorization: ""
    email: ""
    key: ""
  shodan:
    key: ""